/* eslint-disable no-console */
/**
 * Basic Transfer Example
 *
 * The simplest kova usage:
 * 1. Create a wallet with a spending limit policy
 * 2. Check balance
 * 3. Send SOL on the local validator
 *
 * Prerequisites:
 *   - Run ./scripts/local-dev.sh first (starts validator, funds wallet)
 *   - source .env.local
 *
 * Run: npx tsx examples/basic-transfer/index.ts
 */

import { Keypair } from "@solana/web3.js";
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import {
  AgentWallet,
  Policy,
  PolicyEngine,
  SpendingLimitRule,
  RateLimitRule,
  LocalSigner,
  SolanaAdapter,
  MemoryStore,
} from "../../src/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const RPC_URL = process.env.SOLANA_RPC_URL ?? "http://localhost:8899";

async function main() {
  // 1. Load the local keypair (generated by local-dev.sh), or generate a fresh one
  const keypairPath = process.env.LOCAL_KEYPAIR_PATH
    ?? resolve(__dirname, "../../.local-keypair.json");

  let keypair: Keypair;
  try {
    const secretKey = JSON.parse(readFileSync(keypairPath, "utf-8"));
    keypair = Keypair.fromSecretKey(Uint8Array.from(secretKey));
    console.log(`Loaded keypair from ${keypairPath}`);
  } catch {
    console.log("No local keypair found, generating a fresh one (will have 0 SOL)");
    keypair = Keypair.generate();
  }
  console.log(`Wallet address: ${keypair.publicKey.toBase58()}`);

  // Load recipient from env, or from .local-recipient.json, or generate one
  let RECIPIENT = process.env.RECIPIENT_ADDRESS;
  if (!RECIPIENT) {
    try {
      const recipientPath = resolve(__dirname, "../../.local-recipient.json");
      const recipientKey = JSON.parse(readFileSync(recipientPath, "utf-8"));
      RECIPIENT = Keypair.fromSecretKey(Uint8Array.from(recipientKey)).publicKey.toBase58();
    } catch {
      RECIPIENT = Keypair.generate().publicKey.toBase58();
    }
  }
  console.log(`Recipient: ${RECIPIENT}`);

  // 2. Build a policy with spending limits
  const policy = Policy.create("basic-demo")
    .spendingLimit({
      perTransaction: { amount: "0.5", token: "SOL" },
      daily: { amount: "2", token: "SOL" },
    })
    .rateLimit({ maxTransactionsPerMinute: 5 })
    .build();

  // 3. Convert the Policy into a PolicyEngine (required by AgentWallet)
  const store = new MemoryStore();
  const config = policy.toJSON();
  const rules = [];
  if (config.spendingLimit) rules.push(new SpendingLimitRule(config.spendingLimit));
  if (config.rateLimit) rules.push(new RateLimitRule(config.rateLimit));
  const engine = new PolicyEngine(rules, store);

  // 4. Create the wallet
  const wallet = new AgentWallet({
    signer: new LocalSigner(keypair),
    chain: new SolanaAdapter({ rpcUrl: RPC_URL }),
    policy: engine,
    store,
  });

  // 5. Check balance
  const balance = await wallet.getBalance("SOL");
  console.log(`Balance: ${balance.amount} SOL`);

  // 6. View policy constraints
  const policySummary = await wallet.getPolicy();
  console.log("Policy:", JSON.stringify(policySummary, null, 2));

  // 7. Execute a transfer
  console.log(`\nSending 0.01 SOL to ${RECIPIENT}...`);
  const result = await wallet.execute({
    type: "transfer",
    chain: "solana",
    params: { to: RECIPIENT, amount: "0.01", token: "SOL" },
    metadata: { reason: "Basic transfer example" },
  });
  console.log(`Result: [${result.status}] ${result.summary}`);
  if (result.txId) console.log(`Transaction: ${result.txId}`);

  // 8. Check transaction history
  const history = await wallet.getTransactionHistory(5);
  console.log(`\nTransaction history: ${history.length} entries`);
  for (const tx of history) {
    console.log(`  [${tx.status}] ${tx.summary}`);
  }
}

main().catch(console.error);
